#!/bin/bash

# Declaracion variables
NORMAL=$(tput sgr0)
VERDE=$(tput setaf 2; tput bold)
AMARILLO=$(tput setaf 3)
ROJO=$(tput setaf 1)
AZUL=$(tput setaf 4)
BLACK=$(tput setaf 0)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6) 
WHITE=$(tput setaf 7)
 
# Declaracion funciones
function rojo() {
    echo -e "$ROJO$*$NORMAL"
}

function verde() {
    echo -e "$VERDE$*$NORMAL"
}

function amarillo() {
    echo -e "$AMARILLO$*$NORMAL"
}

# Aca empieza el main
# Para imprimir salidas exitosas
verde "La tarea ha finalizado correctamente."

# Para imprimir errores
rojo "La configuración no existe."

# Para imprimir advertencias
amarillo "Debes usar una versión más nueva."

